"""Webmention notifications

Revision ID: 2b51ae7047cb
Revises: e58c1ffadf2e
Create Date: 2022-07-19 20:22:06.968951

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2b51ae7047cb'
down_revision = 'e58c1ffadf2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_webmention_id', 'webmention', ['webmention_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_webmention_id', type_='foreignkey')

    # ### end Alembic commands ###
