"""Alt text for attachments

Revision ID: c9f204f5611d
Revises: 8ae9fc9ac88c
Create Date: 2022-07-21 22:33:41.569754

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9f204f5611d'
down_revision = '8ae9fc9ac88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_object_attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_object_attachment', schema=None) as batch_op:
        batch_op.drop_column('alt')

    # ### end Alembic commands ###
