"""Update support

Revision ID: e58c1ffadf2e
Revises: fd23d95e5c16
Create Date: 2022-07-17 18:19:42.362542

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e58c1ffadf2e'
down_revision = 'fd23d95e5c16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('revisions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox', 'revisions')
    # ### end Alembic commands ###
